export ROOTSYS=/afs/cern.ch/cms/lumi/brilconda-1.1.7/root
export PATH=$ROOTSYS/bin:$PATH
export LD_LIBRARY_PATH=/afs/cern.ch/cms/lumi/brilconda-1.1.7/root/lib
export PYTHONPATH=/afs/cern.ch/cms/lumi/brilconda-1.1.7/root/lib
export PYTHONPATH=$ROOTSYS/lib:$PYTHONPATH
export PYTHONPATH=${PWD}:$PYTHONPATH
export PYTHONPATH=${PWD}/fits:$PYTHONPATH
export PYTHONPATH=${PWD}/corrections:$PYTHONPATH
export VDMPATH=${PWD}
export PATH=/afs/cern.ch/cms/lumi/brilconda-1.1.7/bin:$PATH
#source /afs/cern.ch/cms/lumi/brilconda-1.1.7/root/bin/thisroot.sh
